name: Ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: installing dependencies
      shell: bash
      run: |
        sudo apt -y update
        sudo apt -y install qt5-default libboost-all-dev libcgal-dev libgmp-dev libqglviewer-dev-qt5 libeigen3-dev
    - name: compiling SplitAndMill
      run: |
        qmake SplitAndMill.pro
        make -j4
      
